# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='image/')),
                ('project_title', models.TextField()),
                ('project_description', models.TextField()),
                ('project_link', models.TextField()),
            ],
        ),
    ]
