# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['bio'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='image/')),
                ('project_title', models.TextField()),
                ('project_description', models.TextField()),
                ('project_link', models.TextField()),
                ('post', tinymce.models.HTMLField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
