# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_photo', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['bio'],
            },
        ),
    ]
